version: '3.7'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
      - "7900:7900"  # VNC server for debugging
    shm_size: '2g'
    environment:
      - SE_NODE_SESSION_TIMEOUT=360  # 6 minutes timeout
      - SE_NODE_MAX_SESSIONS=4
    restart: unless-stopped

volumes:
  redis_data: 